services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile
    container_name: init-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./init-db/src:/app/src
    working_dir: /app
    depends_on:
      - postgres

  task-scheduler-api:
    build:
      context: ./task-scheduler-api
      dockerfile: Dockerfile
    container_name: task-scheduler-api
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost:3000/api
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
    depends_on:
      - postgres
      - init-db

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ~/.docker/data/task-scheduler
      o: bind
