# Copyright Talkersoft LLC
# /docker-compose.yml
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile
    container_name: init-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./init-db/src:/app/src
    working_dir: /app
    depends_on:
      - postgres

  task-scheduler-api:
    build:
      context: .
      dockerfile: ./backend/task-scheduler-api/Dockerfile
    container_name: task-scheduler-api
    environment:
      - BASE_URL=http://localhost:5001/api
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - CORS_URLS=http://localhost:3001
    depends_on:
      - postgres
      - init-db
    ports:
      - "5001:5001"
      - "9227:9227"

  task-scheduler:
    build:
      context: .
      dockerfile: ./backend/task-scheduler/Dockerfile
    container_name: task-scheduler
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - SCHEDULE_INTERVAL=60000
    depends_on:
      - postgres
      - init-db
    ports:
      - "9229:9229"

  task-distributor:
    build:
      context: .
      dockerfile: ./backend/task-distributor/Dockerfile
    container_name: task-distributor
    environment:
      - THROTTLE_INTERVAL=500
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    depends_on:
      - postgres
      - init-db
      - rabbitmq
    ports:
      - "9228:9228"


  task-processor-1:
    build:
      context: .
      dockerfile: ./backend/task-processor/Dockerfile
    container_name: task-processor-1
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - API_URL=https://api.namefake.com/english-united-states
      - PROCESSING_MAX_RETRIES=3
    depends_on:
      - init-db
      - rabbitmq

  task-processor-2:
    build:
      context: .
      dockerfile: ./backend/task-processor/Dockerfile
    container_name: task-processor-2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - API_URL=https://api.namefake.com/english-united-states
      - PROCESSING_MAX_RETRIES=3
    depends_on:
      - init-db
      - rabbitmq

  task-processor-3:
    build:
      context: .
      dockerfile: ./backend/task-processor/Dockerfile
    container_name: task-processor-3
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_scheduler
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - API_URL=https://api.namefake.com/english-united-states
      - PROCESSING_MAX_RETRIES=3
    depends_on:
      - init-db
      - rabbitmq

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ~/.docker/data/task-scheduler
      o: bind
